services:
  webservice: 
    build:
      context: .
      dockerfile: ./bin/webserver/Dockerfile
      args:
        PHP_VERSION: ${PHP_VERSION}
    volumes:
      - ./webroot:/var/www/html
      - ./config/php/php.ini:/usr/local/etc/php/php.ini
      - ./config/vhosts:/etc/apache2/sites-enabled
      - ./logs/apache2:/var/log/apache2
    ports:
      - "${HOST_MACHINE_HTTP_PORT}:80"
    
  db_server:
    image: "${DB_SERVER}"
    restart: always
    environment:
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./logs/mysql:/var/log/mysql
    ports:
      - "${HOST_MACHINE_MYSQL_PORT}:3306"
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=db_server
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    ports:
      - "${HOST_MACHINE_PHPMYADMIN_PORT}:80"

